spring.application.name=task-manager-api
properties# ===== Server =====
server.port=8080

# ===== MySQL =====
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/task_manager_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:} 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== Jackson (JSON) =====
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null